### PR TITLE
Assignment#3

### PR DESCRIPTION
**Pull request by JIE2016G**
I selected two questions including how many states have you visited in the US and what city/town did you grow up?

### CODE REVIEW

**Comment by JG1990** [comment]
assignment3-part 1

**Comment by charles-lang** [comment]
Did you manage to create any graphs? I can't see them here?

**Comment by JG1990** [comment]
Dear professor, I have finished assignment#3 part one and part two yesterday afternoon.

**Comment by JG1990** [comment]
Yes professor！I have finished assignment3 yesterday afternoon. I committed and pushed.

发自我的 iPhone

**Pull request closed without merging**
